language: node_js
node_js: stable
cache:
  directories:
    - node_modules
install:
  - npm install
script: npm run build
before_install:
  - export TZ='Asia/Shanghai'
after_success:
  - cd ./dist
  - git init
  - git config --global user.name "cyea"
  - git config --global user.email "yuyehack@gmail.com"
  - git add .
  - t=`date '+%Y-%m-%d %H:%M:%S'`
  - git commit -m "Update site by travis-ci from branch master $t"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/cyea/web-crypto.git
    - secure:
